// Chapter 18/angularapp/src/app/categoryList.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'category-list',
  templateUrl: './categoryList.component.html',
})
export class CategegoryList {
  @Input()
  selected: string = '';

  @Input()
  categories: string[] = [];

  @Output()
  selectCategory = new EventEmitter<string>();

  getBtnClass(category: string): string {
    return (
      'btn btn-block ' +
      (category === this.selected ? 'btn-primary' : 'btn-secondary')
    );
  }
}

<div class="d-grid gap-2">
  <button
    *ngFor="let cat of categories"
    [class]="getBtnClass(cat)"
    (click)="selectCategory.emit(cat)"
  >
    {{ cat }}
  </button>
</div>

// Chapter 16/webapp/src/categoryList.tsx
import { createElement } from "./tools/jsxFactory";

export class CategoryList {
  props: {
    categories: string[];
    selectedCategory: string;
    callback: (selected: string) => void;
  };

  getContent(): HTMLElement {
    return (
      <div className="d-grid gap-2">
        {["All", ...this.props.categories].map((c) =>
          this.getCategoryButton(c)
        )}
      </div>
    );
  }

  getCategoryButton(cat?: string): HTMLElement {
    let selected =
      this.props.selectedCategory === undefined
        ? "All"
        : this.props.selectedCategory;
    let btnClass = selected === cat ? "btn-primary" : "btn-secondary";
    return (
      <button
        className={`btn btn-block ${btnClass}`}
        onclick={() => this.props.callback(cat)}
      >
        {cat}
      </button>
    );
  }
}
